### ISSUE TITLE
Background URL

### ISSUE THREAD

**Issue by Robert3141** [Prodiginus/Frosted#2]
I'm a complete noobie to professional CSS. As a result I cannot tell where the background which is blurred comes from. Please can you mention how to change the background URL in the README.MD. Thanks, and I apologize for my incompetence.

**Comment by Ramlord** [comment]
updated in my fork of the theme

**Comment by Prodiginus** [comment]
Use his fork as I don't really maintain mine because of life getting in the way. But to answer your question, I included variables bg1-3 in the user.css file at the very top, they all have a url in the value and you can change those to any wallpaper you desire, then, within the next few variables there is another variable named "bg". You can use that variable to pick which wallpaper out of the 3 that you want to use simply by changing the name of the value from bg2 to bg3 or bg1.
